name: amoriodi
description: Orina's homepage
version: 1.0.0
homepage: https://www.amoriodi.xyz

environment:
  sdk: ">=2.18.5"

dependencies:
  markdown: ^6.0.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  lints: ^2.0.1
